version: '3.4'

services:

  jobsapp:
    image: jobsapp
    build:
      context: ./JobsApp
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - jobappdb

  jobappdb:
    image: postgres:10.6
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data